version: '2'
services:
  db:
    image: mariadb:11.8.8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=moodledb
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=password
    # environment:
    #   MOODLE_DATABASE_HOST: 'mariadb'
    #   MOODLE_DATABASE_NAME: dev_moodledb
    #   MOODLE_DATABASE_USER: 'devteam'
    #   MOODLE_DATABASE_PASSWORD: 'devcwdb.2025'
    #   MOODLE_SKIP_BOOTSTRAP: 'yes'
    #   MOODLE_SSLPROXY: "true"
    #   MOODLE_INTERNAL_URL: 'http://moodle-app:8080/lms-service'
    volumes:
      - ./database/db:/docker-entrypoint-initdb.d
      - ./database/conf/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf:ro
      - moodle-mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    image: khalibre/moodle-base:v4.5.14
    ports:
      - 8080:8080
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    # uncomment the 'volumes' section to enable a shared volume with docker-compose
    volumes:
      - moodle-data:/moodledata:rw
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=db
      # - MOODLE_DB_PORT= 3306
      - MOODLE_DATABASE_NAME=moodledb
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=password
      # - MOODLE_DATABASE_PREFIX=
      - MOODLE_INTERNAL_URL=http://localhost:8080
      #- MOODLE_SITE_FULLNAME=
      #- MOODLE_SITE_SHORTNAME=
      #- MOODLE_SITE_LANG=
      #=======for fresh start==============
      # - MOODLE_ADMIN_USER=admin
      # - MOODLE_ADMIN_PASS=admin
      #====================================
      #- MOODLE_ADMIN_EMAIL=
      #- MOODLE_UPDATE=
      #- MOODLE_REVERSE_PROXY=false
      #- MOODLE_SSLPROXY=false
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT=6379
      - MOODLE_REDIS_DB=0
      #- MOODLE_REDIS_PREFIX=''
      - MOODLE_DISABLE_UPDATE_AUTODEPLOY=true
      #- MOODLE_DEBUG=true
      #- SMTP_HOST=example.com:465
      #- SMTP_USER=test
      #- SMTP_PASS=testpass
      #- SMTP_SECURITY=ssl
      #- SMTP_AUTH_TYPE=PLAIN
      #- MOODLE_NOREPLY_ADDRESS=test@example.com
  redis:
    image: redis:5.0-alpine
    volumes:
      - moodle-redis-data:/data
    ports:
      - 6379:6379

volumes:
  moodle-data:
  moodle-mariadb-data:
  moodle-redis-data:
